import Head from "next/head";
import Hero from "@/components/Hero";
import Product from "@/components/Product";
import Categorie from "@/components/Categorie";
import History from "@/components/History";

export default function Home() {
  return (
    <>
      <Head>
        <title>Conjunto Pedregal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />     
      </Head>
      <Hero />
      <Product />
      <Categorie />
      <History />
    </>
    
  );
}
