import Head from "next/head";
import Hero from "@/components/Hero";
import Product from "@/components/Product";
import Categorie from "@/components/Categorie";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Pedregal Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Product />
      <Categorie />
    </>
  );
}
